import os
from docx import Document
from docx.shared import Pt

def add_custom_section(doc_path, heading_text, paragraphs):
    if not os.path.exists(doc_path):
        print(f"Skipping (not found): {doc_path}")
        return False
        
    doc = Document(doc_path)
    
    # Add a paragraph for heading
    p_head = doc.add_paragraph()
    p_head.style = 'Heading 2'
    r_head = p_head.add_run(heading_text)
    r_head.bold = True
    r_head.font.name = "Arial"
    r_head.font.size = Pt(13)
    
    # Add paragraphs
    for text in paragraphs:
        p = doc.add_paragraph()
        p.style = 'Normal'
        r = p.add_run(text)
        r.font.name = "Arial"
        r.font.size = Pt(11)
        
    doc.save(doc_path)
    print(f"Successfully patched {os.path.basename(doc_path)} with section '{heading_text}'")
    return True

def main():
    docs_dir = "/Users/user/Desktop/Final_year/docs"
    
    # 1. Patch Volume I
    vol_i_path = os.path.join(docs_dir, "Volume_I_System_Design_and_Architecture.docx")
    vol_i_head = "Decoupled IPC Background Daemon & Universal App Icon Architecture"
    vol_i_paras = [
        "To ensure that the System Resource Optimizer (SRO) performs its core telemetry collection and AI-driven process mitigation operations with zero GUI dependencies, the system architecture has been refactored into a decoupled client-server structure. The core monitoring loops, PyTorch/ONNX inference pipelines, and CPU/Memory action engines run continuously inside a silent background daemon named SystemResourceOptimizerService.",
        "Additionally, the application utilizes a custom-designed, modern, flat-vector logo representing an optimization circular arrow surrounding a central microchip core, rendered with a vibrant emerald-green to electric-blue gradient. The design is integrated natively in high-resolution PNG, vector SVG, compiled macOS .icns, and Windows multi-resolution .ico formats, ensuring visual brand consistency across both operating systems."
    ]
    add_custom_section(vol_i_path, vol_i_head, vol_i_paras)
    
    # 2. Patch Volume II
    vol_ii_path = os.path.join(docs_dir, "Volume_II_Telemetry_and_Model_Documentation.docx")
    vol_ii_head = "Windows Notification Icon & Telemetry Persistence Integrations"
    vol_ii_paras = [
        "For Windows environments, the telemetry pipelines are configured to support the custom icon.ico file generated by Pillow. The icon contains multiple resolutions (from 16x16 up to 256x256) and is passed directly to the plyer notification module, ensuring that Windows toast notifications carry the project's official branding.",
        "The background service telemetry database stores raw and cleaned telemetry frames, which are normalized and aligned for the GRU recurrent neural network. On first startup, calibration data runs for 90 seconds to dynamically generate a localized MinMaxScaler."
    ]
    add_custom_section(vol_ii_path, vol_ii_head, vol_ii_paras)
    
    # 3. Patch Volume III
    vol_iii_path = os.path.join(docs_dir, "Volume_III_Pipeline_UI_and_Verification.docx")
    vol_iii_head = "Decoupled IPC Service Communication & macOS Dock Icon Resolution"
    vol_iii_paras = [
        "The core telemetry processing and AI inference loop is completely decoupled from the Flet dashboard. It runs as a background service process (SystemResourceOptimizerService) that initializes a local IPC TCP socket server bound to port 5050 on loopback address 127.0.0.1.",
        "The Flet dashboard client connects to this socket, requesting real-time telemetry updates (every 0.5s or 1.0s) and system logs via JSON-serialized request-response packets. If the connection is lost, the client automatically attempts to re-establish the connection. However, if the user explicitly stops the service via the Settings page, the dashboard sends a 'shutdown' command, which cleanly terminates the daemon (resuming all suspended background tasks), triggers a final desktop alert, and closes the dashboard GUI window.",
        "To allow users to temporarily pause SRO monitoring without shutting down the IPC socket server, a toggle switch for the 'Background Optimizer Engine' is implemented in the Settings tab. Toggling this OFF stops the active pipeline thread, triggers a notification, and safely resumes all suspended processes, while keeping the socket server active so the client dashboard remains connected and can re-enable the engine at any time.",
        "On macOS, to prevent a duplicate icon showing in the macOS Dock when the background service daemon is launched, the service is packaged as a command-line binary (console=True in the PyInstaller spec file). On Windows, it is packaged as a windowless binary (console=False) to suppress the command prompt pop-up. The Flet GUI bundle specifies LSBackgroundOnly as False in Info.plist to guarantee that macOS registers the main client app in the Dock and displays its custom logo."
    ]
    add_custom_section(vol_iii_path, vol_iii_head, vol_iii_paras)
    
    # 4. Patch Master Doc (System_Resource_Optimizer_Documentation.docx) if it exists
    master_path = os.path.join(docs_dir, "System_Resource_Optimizer_Documentation.docx")
    if os.path.exists(master_path):
        print("Patching unified master academic documentation...")
        add_custom_section(master_path, "Appendix F: Decoupled Background Daemon & Universal Icon Integration", [
            "1. IPC Background Daemon: The SRO application uses a client-server local IPC architecture (port 5050). The background service daemon executes the real-time telemetry collection and PyTorch GRU model inference, enabling it to run continuously in the background. On macOS, this daemon is compiled as a CLI binary (console=True) so it runs silently without registering a duplicate Dock icon. On Windows, it runs without a console window.",
            "2. Background Optimizer Engine Toggle: A toggle switch in the Settings tab allows the user to suspend/resume the active optimizer telemetry and inference thread via IPC. Disabling it resumes all suspended tasks and triggers a notification while maintaining the IPC connection.",
            "3. Universal Icon System: The custom gradient logo (optimization arrow wrapping a microchip core) is natively integrated in PNG, SVG, ICNS (macOS), and ICO (Windows) formats. In the PyInstaller build specification, LSBackgroundOnly is set to False in Info.plist to ensure macOS registers the GUI client in the Dock and processes standard user notifications.",
            "4. Clean Shutdown Sequence: Stopping the background service from the Settings GUI sends a 'shutdown' signal to the IPC socket. The service resumes all suspended tasks, posts a desktop alert, and then exits, after which the GUI client closes its window."
        ])

if __name__ == "__main__":
    main()
